server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: N # 逻辑已删除值(默认为 N)
      logic-not-delete-value: Y # 逻辑未删除值(默认为 Y)



